### ISSUE TITLE
Windows-related error: Escaped character '\w' is not valid.

### ISSUE THREAD

**Issue by EMCL** [nightrome/matconvnet-calvin#16]
Error using textread (line 165)
File not found.

Error in setupFastRcnnRegions (line 23)
trainIms = textread(sprintf(DATAopts.imgsetpath, trainName), '%s'); %#ok<DTXTRD>

Error in demo_frcn (line 20)
setupFastRcnnRegions();

i am getting this error when i am trying to run demo_frcn()

**Comment by nightrome** [comment]
Hi,

if you look at that line `trainIms = textread(sprintf(DATAopts.imgsetpath, trainName), '%s');`, you will see that it is creating a file path out of `DATAopts.imgsetpath` and `trainName`. Since you probably only changed the former, I am suspecting that your imgsetpath includes a backslash before the letter 'w'. So either you confused \ and /, or you are on Windows, in which case the software unfortunately won't work for you.
To debug this, go to [https://github.com/nightrome/matconvnet-calvin/blob/master/matconvnet-calvin/examples/frcn/setupDataOpts.m#L13](https://github.com/nightrome/matconvnet-calvin/blob/master/matconvnet-calvin/examples/frcn/setupDataOpts.m#L13) and trace back those variables.

**Comment by EMCL** [comment]
Hi,
actually, i didn't change anything of code..i want to run this and see results.I am in the window environment.do i need create txt file of image path for see results?
% Setup VOC data
DATAopts.imgsetpath     = [**DATAopts.datadir**, 'ImageSets', '\', 'Main', '\', '%s.txt'];

DATAopts.datadir        = [**devkitroot**, DATAopts.dataset, '\'];
devkitroot = [**datasetDir**, 'VOCdevkit', '\'];
function setupDataOpts(vocYear, testName, **datasetDir**)

**Comment by nightrome** [comment]
Hi,
as I said before, this software does not work on Windows :-(.
Try Caffe2 or Tensorflow instead... [https://github.com/caffe2/caffe2](https://github.com/caffe2/caffe2).

**Comment by EMCL** [comment]
hi,
you mean run in Linux? ok. I will try this.
Thank you.

**Comment by nightrome** [comment]
Exactly. I recommend Ubuntu.

**Comment by EMCL** [comment]
Thank you,.i will try it in Ubuntu.
