### ISSUE TITLE
Matlab C90 mex compiler error: error C2057

### ISSUE THREAD

**Issue by Changjae** [nightrome/matconvnet-calvin#3]
Hi, I'm studying with your matcovnet code and found an error in generating mex file as follows:

Filename: vl_compilenn_calvin.m
mex(mexOpts{:}, fullfile(codeDir, 'misc', 'scoreBlobIoUs.cpp'));

Here, I couldn't generate mex file with my computer due to error C2057 on : 

(66) bool aMaskCut[aMaskCutSizeX \* aMaskCutSizeY];  
(78) bool bMaskCut[bMaskCutSizeX \* bMaskCutSizeY];

I solved the problem by changing them into 

 bool\* aMaskCut = (bool_)mxCalloc(aMaskCutSizeX \* aMaskCutSizeY,sizeof(bool));
 bool_ bMaskCut = (bool*)mxCalloc(bMaskCutSizeX \* bMaskCutSizeY,sizeof(bool));

Please check whether it is right or not. Thank you.

Best Regards, 

Changjae .

**Comment by nightrome** [comment]
Hi, thank you for this interesting observation.
Apparently in C90 the size of an array must be known at run-time, but in C99 it can be flexible.
My gcc 4.9.2. compiler does not generate any errors, but I agree that backward compatibility is desirable.
I think it might also be good to explicitly free the allocated memory, since the function is called repeatedly and the masks can cover the entire image.
I changed it now to the following, which seems to be working fine:

```
bool* aMaskCut = (bool*) mxCalloc(aMaskCutSizeX * aMaskCutSizeY, sizeof(bool));
// ...
mxFree((void*) aMaskCut);
```

I have also provided a simple example to test the Intersection-over-Union computation of two blobs:

```
blobA.rect = [1, 1, 3, 3];
blobA.mask = false(3, 3); blobA.mask(1:2, 2) = true;
blobA.size = sum(blobA.mask(:));

blobB.rect = [2, 2, 4, 4];
blobB.mask = false(4, 4); blobB.mask(1:2, 1) = true;
blobB.size = sum(blobB.mask(:));

iou = scoreBlobIoUs(blobA, blobB);
assert(iou == 1/3);
```

Please reopen this issue if it should persist or if you find similar issues elsewhere.
