### ISSUE TITLE
Selective Search error

### ISSUE THREAD

**Issue by RaymondCS** [nightrome/matconvnet-calvin#9]
Hi,
When I tried to run the code, I encountered an error at first image:

Processing train img: 1/4998
Undefined function or variable 'mexFelzenSegmentIndex'.

Error in Image2HierarchicalGrouping (line 27)
[blobIndIm blobBoxes neighbours] = mexFelzenSegmentIndex(imageToSegment, sigma, k, minSize);

I could find a FelzenSegmentIndex.mexa64 file but it didn't make sense. My laptop is Mac pro with MacOS 10.12. Do you know how to fix it ?

**Comment by nightrome** [comment]
Hi,
that code is actually part of a third party software called Selective Search, which we are just downloading from [http://koen.me/research/selectivesearch/](http://koen.me/research/selectivesearch/). It seems to come with a pre-compiled version for Linux, but if you want to compile it for Mac OS X you will have to run the file `matconvnet-calvin/data/Code/SelectiveSearchCodeIJCV/demo.m`. Please let me know if that fixes it.

**Comment by RaymondCS** [comment]
Hi,
I tried to run demo.m under the directory you said. However, it is said 
Attempt to execute SCRIPT anigauss as a function:
_matconvnet-calvin/data/Code/SelectiveSearchCodeIJCV/Dependencies/anigaussm/anigauss.m_
Do you know how to fix this issue?
Thank you

**Comment by nightrome** [comment]
Are you sure you compiled the Selective Search code by running the demo?
In any case, try to go through the steps in the demo. e.g. for compiling anigauss run
`mex matconvnet-calvin/data/Code/SelectiveSearchCodeIJCV/Dependencies/anigaussm/anigauss_mex.c matconvnet-calvin/data/Code/SelectiveSearchCodeIJCV/Dependencies/anigaussm/anigauss.c -output anigauss`
( https://github.com/sergeyk/selective_search_ijcv_with_python/blob/master/demo.m#L20 ).
Similarly for `mexCountWordsIndex `and `mexFelzenSegmentIndex`.

**Comment by Dmitrivm** [comment]
Actually, there are two different versions of SelectiveSearch package, both available for download here: [(http://homepages.inf.ed.ac.uk/juijling/index.php#page=projects1)]
New one and "deprecated" one.
It is the matter of fact that new package requires pre-build FelzenSegment in Dependencies directory with make command because demo.m script doesn't build it. Maybe by mistake.
Previous one contains prebuilt library.

So you can either use old "deprecated" version either build FelzenSegment library just running "make".

P.S. But anyway I couldn't manage to run demo.m due to another error during image processing. Tomorrow I give the detail information about it.

**Comment by nightrome** [comment]
Hi, thanks for the comment. For the new issue, please open a separate ticket with a meaningful title :-).
